name: swipee
description: Customizable Swipe button widget for Flutter
version: 0.1.0
repository: https://github.com/thatalexay/swipee

environment:
  sdk: '>=3.3.0 <4.0.0'


# Add regular dependencies here.
dependencies:
  flutter:
      sdk: flutter
  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
